server:
  port: 9999
  contextPath: /jooq

pa:
  hazelcast:
    address: localhost
    сonnectionAttemptLimit: 1
    сonnectionAttemptPeriod: 10000
    сonnectionTimeout: 1000

  persistence:
    realmds:
      name: "jdbc/DOCCLOUDDB"
      userTable: "users"
      userNameCol: "userid"
      userCredCol: "password"
      userRoleTable: "user_roles"
      roleNameCol:  "role"
      allRolesMode: "authOnly"

      driverName: "org.postgresql.Driver"
      connectionURL:  "jdbc:postgresql://localhost:5432/doccloud_it"
      connectionName: "doccloud_it"
      connectionPassword: "doccloud_it"
    datasources:
      - name: "jdbc/DOCCLOUDDB"
        factory: "org.apache.tomcat.jdbc.pool.DataSourceFactory"
        driverClassName: "org.postgresql.Driver"
#        url: "jdbc:tc:postgresql:9:6:8:///doccloud?TC_DAEMON=true&TC_INITSCRIPT=file:config/src/main/resources/schema.sql"

        url: "jdbc:postgresql://localhost:5432/doccloud_it"
        maxTotal: "100"
        maxIdle: "20"
        minIdle: "5"
        maxWaitMillis: "10000"
        username: "doccloud_it"
        password: "doccloud_it"
        testOnBorrow: "true"
        testWhileIdle: "true"
        testOnReturn: "true"
        validationQuery: "SELECT 1"
        removeAbandoned: "true"
        removeAbandonedTimeout: "60"
        defaultDS: "true"
        authContainer: "Container"

logging:
  level:
    root: WARN
    ru.doccloud.cmis.server.repository.BridgeRepository: TRACE
    #    ru.doccloud.webapp.*: TRACE
    #    ru.doccloud.service.impl.*: TRACE
    #    org.springframework.cache.*: TRACE
    #    com.hazelcast.core.*: TRACE
    #    ru.doccloud.webapp.config.CachingConfig: TRACE
    #    com.hazelcast.nio.serialization.*: TRACE
#    ru.doccloud.service.impl.*: DEBUG
#    ru.doccloud.google.*: TRACE
#    ru.doccloud.storagemanager.*: TRACE
#    ru.doccloud.repository.impl.JOOQDocumentRepository: TRACE

